#include <stdio.h>
#include "help.h"


void print_help()
{
    printf("%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s",
        "Using: jdate +FORMAT [-f option]\n",
        "Jdate - print the system date and time (in Jalali calendar)\n",
        "Display  the current time/jalali date in the given FORMAT\n",
        "use -f option to print digits using farsi characters.\n\n"
        "FORMAT controls the output.  Interpreted sequences are:\n",
        "%%     a literal %\n",
        "%a     The abbreviated weekday name.\n",
        "%A     The full weekday name.\n",
        "%b     The abbreviated month name.\n",
        "%B     The full month name.\n",
        "%c     The preferred date and time representation.\n",
        "%C     The century number (year/100) as a 2-digit integer.\n",
        "%D     Equivalent to %Y/%m/%d.\n",
        "%e     Like %d, but zero is replaced by a space.\n",
        "%F     Equivalent to %Y-%m-%d.\n",
        "%n     A newline character.\n",
        "%p     Either AM or PM according to the given time value.\n",
        "%P     Like %p but in lowercase: am or pm.\n",
        "%r     equivalent to %I:%M:%S %p (time in am or pm notation).\n",
        "%R     The time in 24-hour notation (%H:%M).\n",
        "%t     A tab character.\n",
        "%T     The time in 24-hour notation (%H:%M:%S).\n",
        "%U     The week  number of the current year as a number.\n",
        "%w     The day of the week as a decimal, range 0 to 6.\n",
        "%x     The preferred date representation without the time.\n",
        "%z     The +hhmm or -hhmm numeric timezone (offset from UTC).\n",
        "%Z     The timezone or name or abbreviation.\n",
        "%q     The full weekday name.\n",
        "%h     The abbreviated weekday name.\n",
        "%d     The day of the month as a decimal number.\n",
        "%m     The month as a decimal number.\n",
        "%j     The day of the year as a decimal number.\n",
        "%k     24-hour clock, single digits are preceded by a blank.\n",
        "%l     12-hour clock, single digits are preceded by a blank.\n",
        "%I     The hour as a decimal number using a 12-hour clock\n",
        "%H     The hour as a decimal number using a 24-hour clock.\n",
        "%M     The minute as a decimal number.\n",
        "%y     The year as a decimal number without a century.\n",
        "%Y     The year as a decimal number including the century.\n",
        "%s     The number of seconds since 1970-01-01 00:00:00.\n",
        "%S     The second as a decimal number.\n",
        "%E     The preferred date and time representation in Farsi.\n",
        "%g     The abbreviated weekday name.\n",
        "%G     The full weekday name.\n",
        "%u     The day of the week as a decimal, range 1 to 7.\n",
        "%v     The abbreviated month name.\n",
        "%V     The full month name.\n",
        "%0     Either ﻕ.ﻅ or ﺏ.ﻅ according to the given time value.\n",
        "%W     The preferred date representation without the time.\n",
        "%X     The preferred time representation in Farsi.\n"
        "Non of the above. Ignoring modifier.\n\n",
        "%10x    prints at least 10 characters including the value of %x\n",
        "%010x   like %10x but space is replaced by a zero character.\n",
        "Note that each farsi character is equal to 2 ascii characters,\n"
        "for more information, see the UTF-8 standard.\n");
}
